version: '3.9'

services:
  products-api:
    build: .
    ports:
      - "3000:8088"
    environment:
      PORT: 8088
      ENVIRONMENT: PRODUCTION
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    #      ENVIRONMENT: DEVELOPMENT
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    container_name: products-sku-api
    depends_on:
      - postgres
    networks:
      - some-net
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    networks:
      - some-net
    container_name: products-sku-api-db
    volumes:
      - ./data:/var/lib/postgresql/data
       #- "./data:/var/lib/postgresql/data:rw"
#      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  some-net:
    driver: bridge