version: '3.1'

services:
  products-api:
    build: .
    ports:
      - "3000:8088"
    environment:
      port: 8088
      ENVIRONMENT: DEVELOPMENT
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    container_name: products-sku-api
    depends_on:
      - pgdb-dev

  pgdb-dev:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: product-sku-api-db
      #- "./data:/var/lib/postgresql/data:rw"
#  admin:
#    image: adminer
#    ports:
#      - 8089:8080