name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main,develop]
env:
  GO111MODULE: on
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Vet and build
        run: |
          go vet ./...
          go build ./...

      - name: Install mockgen
        run: |
          go get github.com/golang/mock/mockgen@v1.6.0
#          go install github.com/golang/mock/mockgen

      - name: Run Go tests all
        if: ${{ startsWith(matrix.go-version, '1.18') }}
        run: |
          for i in $(find $PWD -name go.mod); do
            pushd $(dirname $i)
            go test ./...
            popd
          done 

      - name: Run Go tests some
        if: ${{ startsWith(matrix.go-version, '1.18') == false }}
        run: |
          go test ./...